### ISSUE TITLE
rangement

### ISSUE THREAD

**Issue by yohann-kevin** [soniabzh51/projet#3]
saluuuuuuuuuuuuut

voudrais-tu que je range tes fichiers ? c'est un peut le bazard tu a plusieurs dossier image et tes fichiers .js sont mélange avec les .html.
Je te propose de tout ranger et de refaire les liens qu'en dis-tu ?

cordialement,
plop

**Comment by soniabzh51** [comment]
Bob ben je vais embaucher une femme de ménage alors !!!

**Comment by yohann-kevin** [comment]
Das ist eine sehr gute Idee
